In [7]:
import numpy as np

A = np.array([[2,1],[1,3]])

print(A)
print("shape of A: " + str(A.shape))

[[2 1]
 [1 3]]
shape of A: (2, 2)


In [5]:
cal = A.sum(axis=0)
print(cal,cal.shape)

[ 59.  239.  155.4  76.9] (4,)


In [6]:
percentage = 100*A/cal.reshape(1,4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]
